LangString addOrReinstall ${LANG_ENGLISH} "Reinstall MyLIST"
LangString alreadyInstalled ${LANG_ENGLISH} "MyLIST is already installed"
LangString alreadyInstalledLong ${LANG_ENGLISH} "MyLIST ${VERSION} is already installed. Continue with installation?"
LangString appRunning ${LANG_ENGLISH} "Please close MyLIST, then click Continue."
LangString appRunningOkKill ${LANG_ENGLISH} "MyLIST is running.$\nClose it and continue?"
LangString chooseMaintenanceOption ${LANG_ENGLISH} "Choose an action for the installed version."
LangString choowHowToInstall ${LANG_ENGLISH} "Choose whether to install this version."
LangString createDesktop ${LANG_ENGLISH} "Create desktop shortcut"
LangString dontUninstall ${LANG_ENGLISH} "Keep the installed version"
LangString dontUninstallDowngrade ${LANG_ENGLISH} "Keep the installed version (downgrade is unavailable)"
LangString failedToKillApp ${LANG_ENGLISH} "MyLIST could not be closed. Please close it manually and try again."
LangString installingWebview2 ${LANG_ENGLISH} "Installing WebView2 runtime..."
LangString newerVersionInstalled ${LANG_ENGLISH} "A newer MyLIST version is installed. Install this older version anyway?"
LangString older ${LANG_ENGLISH} "older"
LangString olderOrUnknownVersionInstalled ${LANG_ENGLISH} "An older MyLIST version is installed. Install this version?"
LangString silentDowngrades ${LANG_ENGLISH} "Downgrade is unavailable in silent mode. Please use the installer window."
LangString unableToUninstall ${LANG_ENGLISH} "Uninstall failed. Please try again."
LangString uninstallApp ${LANG_ENGLISH} "Uninstall ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_ENGLISH} "Uninstall and install"
LangString unknown ${LANG_ENGLISH} "unknown"
LangString webview2AbortError ${LANG_ENGLISH} "WebView2 installation failed. Please retry or download it manually."
LangString webview2DownloadError ${LANG_ENGLISH} "WebView2 download failed. Please retry or download it manually."
LangString webview2DownloadSuccess ${LANG_ENGLISH} "WebView2 runtime downloaded."
LangString webview2Downloading ${LANG_ENGLISH} "Preparing WebView2 runtime..."
LangString webview2InstallError ${LANG_ENGLISH} "WebView2 installation failed. Please retry or download it manually."
LangString webview2InstallSuccess ${LANG_ENGLISH} "WebView2 runtime installed."
LangString deleteAppData ${LANG_ENGLISH} "Delete application data"

; Minimal MyLIST installer copy
LangString MUI_TEXT_WELCOME_INFO_TITLE ${LANG_ENGLISH} "MyLIST"
LangString MUI_TEXT_WELCOME_INFO_TEXT ${LANG_ENGLISH} "Install MyLIST on this computer."
LangString MUI_TEXT_DIRECTORY_TITLE ${LANG_ENGLISH} "Install MyLIST"
LangString MUI_TEXT_DIRECTORY_SUBTITLE ${LANG_ENGLISH} "Choose where MyLIST should be installed."
LangString MUI_TEXT_INSTALLING_TITLE ${LANG_ENGLISH} "Installing MyLIST"
LangString MUI_TEXT_INSTALLING_SUBTITLE ${LANG_ENGLISH} "Please wait."
LangString MUI_TEXT_FINISH_TITLE ${LANG_ENGLISH} "MyLIST is ready"
LangString MUI_TEXT_FINISH_SUBTITLE ${LANG_ENGLISH} "Installation complete."
