import React, { useEffect, useRef, useState } from "react";
import ReactDOM from "react-dom/client";
import { invoke } from "@tauri-apps/api/core";
import { getCurrentWindow } from "@tauri-apps/api/window";
import { Checkmark16Regular, FolderOpen20Regular, Globe20Regular } from "@fluentui/react-icons";
import wordmark from "../../src/assets/mylist-wordmark.svg";
import closeIcon from "../../public/icons/dismiss_20_regular.svg";
import "./style.css";

type State = "ready" | "working" | "complete" | "error";
type Mode = "installer" | "uninstaller";
type Locale = "zh-CN" | "zh-TW" | "en" | "de" | "fr" | "it" | "es" | "ja";
type Copy = { language:string; close:string; slogan:string; installDirectory:string; browse:string; install:string; deleteData:string; uninstall:string; installProgress:string; uninstallProgress:string; installing:string; uninstalling:string; openNow:string; done:string; folderTitle:string; directoryRequired:string; directoryAbsolute:string; installUnsupported:string; prepareInstaller:string; startInstaller:string; installFailed:string; saveLanguage:string; uninstallDirectoryUnknown:string; uninstallCoreMissing:string; uninstallFilesBusy:string; startUninstaller:string; uninstallFailed:string; mainMissing:string; startMain:string; genericError:string };

const locales: { id: Locale; label: string }[] = [
  { id:"en", label:"English" }, { id:"de", label:"Deutsch" }, { id:"fr", label:"Français" },
  { id:"it", label:"Italiano" }, { id:"es", label:"Español" }, { id:"ja", label:"日本語" },
  { id:"zh-CN", label:"简体中文" }, { id:"zh-TW", label:"繁體中文" },
];

const copy: Record<Locale, Copy> = {
  "zh-CN": { language:"语言", close:"关闭", slogan:"行动从清单开始", installDirectory:"安装目录", browse:"浏览安装目录", install:"安装", deleteData:"删除所有事项数据", uninstall:"开始卸载", installProgress:"安装进度", uninstallProgress:"卸载进度", installing:"正在安装 MyLIST…", uninstalling:"正在卸载 MyLIST…", openNow:"立即打开", done:"完成", folderTitle:"选择 MyLIST 安装目录", directoryRequired:"请选择安装目录", directoryAbsolute:"安装目录必须是完整路径", installUnsupported:"当前程序不支持安装", prepareInstaller:"无法准备安装文件", startInstaller:"无法启动安装程序", installFailed:"安装未完成", saveLanguage:"无法保存界面语言", uninstallDirectoryUnknown:"无法确定 MyLIST 安装目录", uninstallCoreMissing:"未找到 MyLIST 卸载核心", uninstallFilesBusy:"程序文件仍被占用，请关闭 MyLIST 后重试卸载", startUninstaller:"无法启动卸载程序", uninstallFailed:"卸载未完成", mainMissing:"未找到已安装的 MyLIST 主程序", startMain:"无法启动 MyLIST", genericError:"操作未完成" },
  "zh-TW": { language:"語言", close:"關閉", slogan:"行動從清單開始", installDirectory:"安裝目錄", browse:"瀏覽安裝目錄", install:"安裝", deleteData:"刪除所有事項資料", uninstall:"開始解除安裝", installProgress:"安裝進度", uninstallProgress:"解除安裝進度", installing:"正在安裝 MyLIST…", uninstalling:"正在解除安裝 MyLIST…", openNow:"立即開啟", done:"完成", folderTitle:"選擇 MyLIST 安裝目錄", directoryRequired:"請選擇安裝目錄", directoryAbsolute:"安裝目錄必須是完整路徑", installUnsupported:"目前程式不支援安裝", prepareInstaller:"無法準備安裝檔案", startInstaller:"無法啟動安裝程式", installFailed:"安裝未完成", saveLanguage:"無法儲存介面語言", uninstallDirectoryUnknown:"無法確定 MyLIST 安裝目錄", uninstallCoreMissing:"找不到 MyLIST 解除安裝核心", uninstallFilesBusy:"程式檔案仍被占用，請關閉 MyLIST 後重試", startUninstaller:"無法啟動解除安裝程式", uninstallFailed:"解除安裝未完成", mainMissing:"找不到已安裝的 MyLIST 主程式", startMain:"無法啟動 MyLIST", genericError:"操作未完成" },
  en: { language:"Language", close:"Close", slogan:"Action starts with a list", installDirectory:"Install location", browse:"Browse install location", install:"Install", deleteData:"Delete all task data", uninstall:"Uninstall", installProgress:"Installation progress", uninstallProgress:"Uninstallation progress", installing:"Installing MyLIST…", uninstalling:"Uninstalling MyLIST…", openNow:"Open now", done:"Done", folderTitle:"Choose MyLIST install location", directoryRequired:"Choose an install location", directoryAbsolute:"Enter a complete install path", installUnsupported:"This program cannot install MyLIST", prepareInstaller:"Could not prepare the installer", startInstaller:"Could not start the installer", installFailed:"Installation did not finish", saveLanguage:"Could not save the interface language", uninstallDirectoryUnknown:"Could not determine the MyLIST install location", uninstallCoreMissing:"MyLIST uninstaller core was not found", uninstallFilesBusy:"Program files are still in use. Close MyLIST and try again", startUninstaller:"Could not start the uninstaller", uninstallFailed:"Uninstallation did not finish", mainMissing:"The installed MyLIST app was not found", startMain:"Could not start MyLIST", genericError:"The operation did not finish" },
  de: { language:"Sprache", close:"Schließen", slogan:"Handeln beginnt mit einer Liste", installDirectory:"Installationsort", browse:"Installationsort auswählen", install:"Installieren", deleteData:"Alle Aufgabendaten löschen", uninstall:"Deinstallieren", installProgress:"Installationsfortschritt", uninstallProgress:"Deinstallationsfortschritt", installing:"MyLIST wird installiert…", uninstalling:"MyLIST wird deinstalliert…", openNow:"Jetzt öffnen", done:"Fertig", folderTitle:"MyLIST-Installationsort auswählen", directoryRequired:"Installationsort auswählen", directoryAbsolute:"Vollständigen Installationspfad eingeben", installUnsupported:"Dieses Programm kann MyLIST nicht installieren", prepareInstaller:"Installationsdateien konnten nicht vorbereitet werden", startInstaller:"Installationsprogramm konnte nicht gestartet werden", installFailed:"Installation wurde nicht abgeschlossen", saveLanguage:"Oberflächensprache konnte nicht gespeichert werden", uninstallDirectoryUnknown:"MyLIST-Installationsort konnte nicht ermittelt werden", uninstallCoreMissing:"MyLIST-Deinstallationskern wurde nicht gefunden", uninstallFilesBusy:"Programmdateien werden noch verwendet. MyLIST schließen und erneut versuchen", startUninstaller:"Deinstallationsprogramm konnte nicht gestartet werden", uninstallFailed:"Deinstallation wurde nicht abgeschlossen", mainMissing:"Installierte MyLIST-App wurde nicht gefunden", startMain:"MyLIST konnte nicht gestartet werden", genericError:"Vorgang wurde nicht abgeschlossen" },
  fr: { language:"Langue", close:"Fermer", slogan:"L’action commence par une liste", installDirectory:"Dossier d’installation", browse:"Choisir le dossier d’installation", install:"Installer", deleteData:"Supprimer toutes les données", uninstall:"Désinstaller", installProgress:"Progression de l’installation", uninstallProgress:"Progression de la désinstallation", installing:"Installation de MyLIST…", uninstalling:"Désinstallation de MyLIST…", openNow:"Ouvrir", done:"Terminer", folderTitle:"Choisir le dossier d’installation de MyLIST", directoryRequired:"Choisissez un dossier d’installation", directoryAbsolute:"Saisissez un chemin d’installation complet", installUnsupported:"Ce programme ne peut pas installer MyLIST", prepareInstaller:"Impossible de préparer l’installation", startInstaller:"Impossible de démarrer l’installation", installFailed:"L’installation n’est pas terminée", saveLanguage:"Impossible d’enregistrer la langue de l’interface", uninstallDirectoryUnknown:"Impossible de déterminer le dossier d’installation de MyLIST", uninstallCoreMissing:"Le composant de désinstallation de MyLIST est introuvable", uninstallFilesBusy:"Des fichiers sont encore utilisés. Fermez MyLIST et réessayez", startUninstaller:"Impossible de démarrer la désinstallation", uninstallFailed:"La désinstallation n’est pas terminée", mainMissing:"L’application MyLIST installée est introuvable", startMain:"Impossible de démarrer MyLIST", genericError:"L’opération n’est pas terminée" },
  it: { language:"Lingua", close:"Chiudi", slogan:"L’azione inizia da una lista", installDirectory:"Percorso di installazione", browse:"Scegli il percorso di installazione", install:"Installa", deleteData:"Elimina tutti i dati delle attività", uninstall:"Disinstalla", installProgress:"Avanzamento installazione", uninstallProgress:"Avanzamento disinstallazione", installing:"Installazione di MyLIST…", uninstalling:"Disinstallazione di MyLIST…", openNow:"Apri ora", done:"Fine", folderTitle:"Scegli il percorso di installazione di MyLIST", directoryRequired:"Scegli un percorso di installazione", directoryAbsolute:"Inserisci un percorso di installazione completo", installUnsupported:"Questo programma non può installare MyLIST", prepareInstaller:"Impossibile preparare l’installazione", startInstaller:"Impossibile avviare l’installazione", installFailed:"Installazione non completata", saveLanguage:"Impossibile salvare la lingua dell’interfaccia", uninstallDirectoryUnknown:"Impossibile determinare il percorso di MyLIST", uninstallCoreMissing:"Componente di disinstallazione MyLIST non trovato", uninstallFilesBusy:"I file sono ancora in uso. Chiudi MyLIST e riprova", startUninstaller:"Impossibile avviare la disinstallazione", uninstallFailed:"Disinstallazione non completata", mainMissing:"App MyLIST installata non trovata", startMain:"Impossibile avviare MyLIST", genericError:"Operazione non completata" },
  es: { language:"Idioma", close:"Cerrar", slogan:"La acción empieza con una lista", installDirectory:"Ubicación de instalación", browse:"Elegir ubicación de instalación", install:"Instalar", deleteData:"Eliminar todos los datos de tareas", uninstall:"Desinstalar", installProgress:"Progreso de instalación", uninstallProgress:"Progreso de desinstalación", installing:"Instalando MyLIST…", uninstalling:"Desinstalando MyLIST…", openNow:"Abrir ahora", done:"Finalizar", folderTitle:"Elegir ubicación de instalación de MyLIST", directoryRequired:"Elige una ubicación de instalación", directoryAbsolute:"Introduce una ruta de instalación completa", installUnsupported:"Este programa no puede instalar MyLIST", prepareInstaller:"No se pudo preparar la instalación", startInstaller:"No se pudo iniciar la instalación", installFailed:"La instalación no finalizó", saveLanguage:"No se pudo guardar el idioma de la interfaz", uninstallDirectoryUnknown:"No se pudo determinar la ubicación de MyLIST", uninstallCoreMissing:"No se encontró el núcleo de desinstalación de MyLIST", uninstallFilesBusy:"Hay archivos en uso. Cierra MyLIST e inténtalo de nuevo", startUninstaller:"No se pudo iniciar la desinstalación", uninstallFailed:"La desinstalación no finalizó", mainMissing:"No se encontró la aplicación MyLIST instalada", startMain:"No se pudo iniciar MyLIST", genericError:"La operación no finalizó" },
  ja: { language:"言語", close:"閉じる", slogan:"行動はリストから始まる", installDirectory:"インストール先", browse:"インストール先を選択", install:"インストール", deleteData:"すべてのタスクデータを削除", uninstall:"アンインストール", installProgress:"インストールの進行状況", uninstallProgress:"アンインストールの進行状況", installing:"MyLIST をインストール中…", uninstalling:"MyLIST をアンインストール中…", openNow:"今すぐ開く", done:"完了", folderTitle:"MyLIST のインストール先を選択", directoryRequired:"インストール先を選択してください", directoryAbsolute:"完全なインストールパスを入力してください", installUnsupported:"このプログラムでは MyLIST をインストールできません", prepareInstaller:"インストールファイルを準備できませんでした", startInstaller:"インストーラーを起動できませんでした", installFailed:"インストールが完了しませんでした", saveLanguage:"表示言語を保存できませんでした", uninstallDirectoryUnknown:"MyLIST のインストール先を特定できませんでした", uninstallCoreMissing:"MyLIST のアンインストールコアが見つかりません", uninstallFilesBusy:"ファイルが使用中です。MyLIST を閉じて再試行してください", startUninstaller:"アンインストーラーを起動できませんでした", uninstallFailed:"アンインストールが完了しませんでした", mainMissing:"インストール済みの MyLIST が見つかりません", startMain:"MyLIST を起動できませんでした", genericError:"操作が完了しませんでした" },
};

function normalizeLocale(value: string): Locale { const v=value.toLowerCase(); if(["zh-tw","zh-hk","zh-mo"].includes(v)) return "zh-TW"; if(v.startsWith("zh")) return "zh-CN"; const language=v.split("-")[0] as Locale; return locales.some((item)=>item.id===language)?language:"en"; }
function localizeError(value:unknown,t:Copy):string { const raw=String(value).replace(/^Error:\s*/,""); const [code,...parts]=raw.split(":"); const detail=parts.join(":").trim(); const messages:Record<string,string>={ERR_INSTALL_NOT_SUPPORTED:t.installUnsupported,ERR_DIRECTORY_REQUIRED:t.directoryRequired,ERR_DIRECTORY_ABSOLUTE:t.directoryAbsolute,ERR_PREPARE_INSTALLER:t.prepareInstaller,ERR_START_INSTALLER:t.startInstaller,ERR_INSTALL_FAILED:t.installFailed,ERR_SAVE_LANGUAGE:t.saveLanguage,ERR_UNINSTALL_DIRECTORY_UNKNOWN:t.uninstallDirectoryUnknown,ERR_UNINSTALL_CORE_MISSING:t.uninstallCoreMissing,ERR_UNINSTALL_FILES_BUSY:t.uninstallFilesBusy,ERR_START_UNINSTALLER:t.startUninstaller,ERR_UNINSTALL_FAILED:t.uninstallFailed,ERR_MAIN_MISSING:t.mainMissing,ERR_START_MAIN:t.startMain}; const message=messages[code]; return message?(detail?`${message} (${detail})`:message):raw||t.genericError; }

function App() {
  const [mode,setMode]=useState<Mode>("installer"); const [locale,setLocale]=useState<Locale>(()=>normalizeLocale(navigator.language)); const [languageOpen,setLanguageOpen]=useState(false); const [directory,setDirectory]=useState(""); const [deleteData,setDeleteData]=useState(false); const [state,setState]=useState<State>("ready"); const [error,setError]=useState(""); const [progress,setProgress]=useState(0); const languageArea=useRef<HTMLDivElement>(null); const t=copy[locale];
  useEffect(()=>{void Promise.all([invoke<Mode>("shell_mode"),invoke<string>("system_locale")]).then(([shellMode,systemLocale])=>{setMode(shellMode);setLocale(normalizeLocale(systemLocale));if(shellMode==="installer")void invoke<string>("default_install_directory").then(setDirectory);});},[]);
  useEffect(()=>{const close=(event:PointerEvent)=>{if(!languageArea.current?.contains(event.target as Node))setLanguageOpen(false);};window.addEventListener("pointerdown",close);return()=>window.removeEventListener("pointerdown",close);},[]);
  useEffect(()=>{const close=(event:KeyboardEvent)=>{if(event.key==="Escape")setLanguageOpen(false);};window.addEventListener("keydown",close);return()=>window.removeEventListener("keydown",close);},[]);
  const browse=async()=>{const value=await invoke<string|null>("choose_install_directory",{current:directory,locale});if(value)setDirectory(value);};
  const run=async()=>{if(mode==="installer"&&!directory.trim())return;setError("");setProgress(8);setState("working");const timer=window.setInterval(()=>setProgress((value)=>value>=90?90:Math.min(90,value+Math.max(1,Math.ceil((90-value)*.08)))),180);try{if(mode==="installer")await invoke("install_mylist",{directory:directory.trim(),locale});else await invoke("uninstall_mylist",{deleteData});window.clearInterval(timer);setProgress(100);await new Promise((resolve)=>window.setTimeout(resolve,260));setState("complete");}catch(cause){window.clearInterval(timer);setError(String(cause));setState("error");}};
  const finish=async()=>{if(mode==="installer"){try{await invoke("launch_mylist",{directory});}catch(cause){setError(String(cause));setState("error");return;}}await getCurrentWindow().close();}; const busy=state==="working";
  return <main className="shell" lang={locale}><header onMouseDown={(event)=>{if(event.button===0&&!(event.target as HTMLElement).closest("button"))void getCurrentWindow().startDragging();}}><div className="language-area" ref={languageArea}><button className={`window-control language ${languageOpen?"active":""}`} aria-label={t.language} title={t.language} aria-haspopup="menu" aria-expanded={languageOpen} onClick={()=>setLanguageOpen((value)=>!value)}><Globe20Regular aria-hidden="true" /></button>{languageOpen&&<div className="language-menu" role="menu" aria-label={t.language}>{locales.map((item)=><button key={item.id} role="menuitemradio" aria-checked={locale===item.id} onClick={()=>{setLocale(item.id);setLanguageOpen(false);}}><span>{locale===item.id&&<Checkmark16Regular aria-hidden="true"/>}</span>{item.label}</button>)}</div>}</div><button className="window-control close" aria-label={t.close} title={t.close} disabled={busy} onClick={()=>void getCurrentWindow().close()}><img src={closeIcon} alt=""/></button></header><section className="brand"><img src={wordmark} alt="MyLIST"/><p>{t.slogan}</p></section><section className={`panel ${busy||state==="complete"?"panel-centered":""}`} aria-live="polite">
    {mode==="installer"&&(state==="ready"||state==="error")&&<><div className="field"><input aria-label={t.installDirectory} value={directory} onChange={(event)=>setDirectory(event.target.value)}/><button aria-label={t.browse} title={t.browse} onClick={()=>void browse()}><FolderOpen20Regular aria-hidden="true"/></button></div>{error&&<p className="error">{localizeError(error,t)}</p>}<button className="primary" disabled={!directory.trim()} onClick={()=>void run()}>{t.install}</button></>}
    {mode==="uninstaller"&&(state==="ready"||state==="error")&&<><label className="check"><input type="checkbox" checked={deleteData} onChange={(event)=>setDeleteData(event.target.checked)}/><span><Checkmark16Regular/></span><b>{t.deleteData}</b></label>{error&&<p className="error">{localizeError(error,t)}</p>}<button className="primary" onClick={()=>void run()}>{t.uninstall}</button></>}
    {busy&&<div className="status"><div className="progress" role="progressbar" aria-label={mode==="installer"?t.installProgress:t.uninstallProgress} aria-valuemin={0} aria-valuemax={100} aria-valuenow={progress}><i style={{width:`${progress}%`}}/></div><p>{mode==="installer"?t.installing:t.uninstalling}</p></div>}
    {state==="complete"&&<div className="status"><button className="primary" onClick={()=>void finish()}>{mode==="installer"?t.openNow:t.done}</button></div>}
  </section></main>;
}
ReactDOM.createRoot(document.getElementById("root")!).render(<React.StrictMode><App/></React.StrictMode>);
